---
title: "PLS scratchpad #4"
output: html_notebook
---

Status: Component functions work with the zip files; adding features/error handling/options/check for duplicates/be better about testing. Ideally make file path situation less brittle; realistically revising that may end up happening when I have access to deploying it on the cloud anyway so I can live with "the code works but it'll need a hand moving into its new home" given how nebulous that home is for now. Also need to take a breather after this and do the non-Roxygen documentation on bookdown project.

Breakpoint 04/03:
- `get_pls_urls()` runs successfully to return relevant URLs
- `get_pls_data()` is vectorized in parallel over URL results to process available years and clean up after itself; does not have other logging; isn't downloading duplicate zips but is overwriting existing CSVs 

For `targets` usage I think I *don't* actually want to prioritize having a wrapper covering both of those, *but* it's probably a useful exercise because if it doesn't work that's weird and shouldn't happen?

Cleanup:
- [ ] Documentation more complete, there's some with less effort than the other and they should inherit parameter descriptions
- [ ] They should also inherit default *parameters*, except the optional wrapper 
- [x] Test Roxygen build to see if I'm using it correctly, also 
- [ ] Improve unit testing?

Checking the `rvest` results from the IMLS page would require pinging it anyway so I might as well do that every time unless worried about having to be offline? This sounds like something that can wait to put safety rails on for a while yet, one way or another.

Things to regroup:
- [ ] Centralize that kind of idle thought/to-do list 
- [ ] Note reasons for package here and bookdown project adjacent even if I'm planning on canonical non-Roxygen documentation waiting until there's canonical code too 

```{r}

```


